# TZ
# VWARDEN_PSQL_DB
# VWARDEN_PSQL_USER
# VWARDEN_PSQL_PASSWORD
# VWARDEN_HTTP_SCHEMA
# VWARDEN_DOMAIN
# VWARDEN_ADMIN_TOKEN
version: '3'

services:
  vaultwarden-pg:
    image: postgres:16.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=${VWARDEN_PSQL_DB}
      - POSTGRES_USER=${VWARDEN_PSQL_USER}
      - POSTGRES_PASSWORD=${VWARDEN_PSQL_PASSWORD}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /srv/data/vaultwarden-pg/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m

  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:latest-alpine
    restart: always
    depends_on:
      - vaultwarden-pg
    environment:
      - "TZ=${TZ:-Etc/UTC}"
      - "DOMAIN=${VWARDEN_HTTP_SCHEMA:-https}://${VWARDEN_DOMAIN}"
      - "SIGNUPS_ALLOWED=false"
      - "ADMIN_TOKEN=${VWARDEN_ADMIN_TOKEN}"
      - "DATABASE_URL=postgresql://${VWARDEN_PSQL_USER}:${VWARDEN_PSQL_PASSWORD}@vaultwarden-pg:5432/${VWARDEN_PSQL_DB}"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /srv/data/vaultwarden:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden-https.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden-https.priority=201"
      - "traefik.http.routers.vaultwarden-https.rule=(Host(`${VWARDEN_DOMAIN}`))"
      - "traefik.http.routers.vaultwarden-https.service=vaultwarden"
      - "traefik.http.routers.vaultwarden-https.tls=true"
      - "traefik.http.routers.vaultwarden-https.tls.certresolver=le"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
      - "traefik.http.services.vaultwarden.loadbalancer.server.scheme=http"
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
