version: '3.9'

services:
  ollama:
    image: ghcr.io/xaemiphor/litellm-ollama:main
    restart: unless-stopped
    ports:
      - ${LITELLM_PORT:-8000}:${LITELLM_PORT:-8000}
      - ${OLLAMA_PORT:-11434}:${OLLAMA_PORT:-11434}
    volumes:
      - /srv/data/ollama:/root/.ollama
    environment:
      LITELLM_HOST: 0.0.0.0
      LITELLM_PORT: ${LITELLM_PORT:-8000}
      OLLAMA_HOST: "0.0.0.0:${OLLAMA_PORT:-11434}"
      OLLAMA_PULL: tinydolphin:latest
